version: '3.8'
services:
  spring-boot-app:
    image: vietlecd/devjava:latest
    ports:
      - "8000:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
