---
server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api
jwt:
  expiration: 360000
  secretKey: ${JWT_SECRET_KEY}
vnp:
  tmnCode: ${vnp_TmnCode}
  secretCode: ${vnp_SecretKey}

google-drive:
    folder-id: ${GOOGLE_DRIVE_FOLDER_ID}
